In [3]:
import numpy as np
N = 10  
array = np.random.rand(N)
mean = np.mean(array)
variance = np.var(array)

print(f"Array: {array}")
print(f"Mean: {mean}")
print(f"Variance: {variance}")

m = sum(array) / N
print(m)
v = sum((xi - mean) ** 2 for xi in array) / N
print(v)

Array: [0.23222743 0.4064537  0.96113383 0.96062036 0.46645685 0.44308922
 0.09694334 0.18443454 0.28934102 0.94805557]
Mean: 0.49887558717112734
Variance: 0.10167871557792038


In [4]:
import numpy as np
M = 10 
X = np.random.rand(M)
Y = np.random.rand(M)
mean_X = np.mean(X)
mean_Y = np.mean(Y)

# Calculate covariance manually
covariance = sum((X[i] - mean_X) * (Y[i] - mean_Y) for i in range(M)) / M
print(f"Vector X: {X}")
print(f"Vector Y: {Y}")
print(f"Mean of Vector X: {mean_X}")
print(f"Mean of Vector Y: {mean_Y}")
print(f"Covariance: {covariance}")

# Calculate covariance using inbuilt function
covariance_matrix = np.cov(Y, bias=True)
covx = covariance_matrix[0, 1]
print(covx)

Vector X: [0.50244501 0.23797946 0.22125459 0.97650555 0.40814225 0.56153897
 0.89373176 0.1261063  0.8653368  0.35019369]
Vector Y: [0.47980196 0.40025372 0.24481264 0.76424628 0.13612683 0.14335192
 0.9166204  0.34438524 0.41270219 0.49642992]
Mean of Vector X: 0.5143234385606912
Mean of Vector Y: 0.43387311050821237
Covariance: 0.0434943550636643
0.04349435506366431


In [5]:
import numpy as np

N = 10 
X = np.random.rand(N)
Y = np.random.rand(N)

correlation_matrix = np.corrcoef(X, Y)
correlation = correlation_matrix[0, 1]  # Extract the correlation value
print(f"Vector X: {X}")
print(f"Vector Y: {Y}")
print(f"Correlation: {correlation}")


Vector X: [0.78141198 0.85433745 0.14428691 0.29236332 0.74058893 0.85409736
 0.19710278 0.34929945 0.86215962 0.50163945]
Vector Y: [0.70996902 0.15512109 0.93053207 0.33912751 0.40345371 0.75973881
 0.12032879 0.22550553 0.6677379  0.70074041]
Correlation: 0.1360512456607195


In [6]:
import numpy as np
M = 4  # Number of features
N = 10  # Number of samples
matrix = np.random.rand(M, N)

covariance_matrix = np.cov(matrix, rowvar=True, bias=True)
correlation_matrix = np.corrcoef(matrix)
print("Matrix (M x N):")
print(matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Matrix (M x N):
[[0.67911585 0.02921117 0.27159168 0.35742261 0.45808762 0.26438751
  0.39100788 0.42328388 0.8375112  0.86986524]
 [0.89598433 0.64222442 0.2780442  0.78961883 0.92770874 0.93770493
  0.92322077 0.45354344 0.50980532 0.28124608]
 [0.0018381  0.98970822 0.98649178 0.38421164 0.16214659 0.74244168
  0.78930931 0.63770569 0.45924841 0.16654063]
 [0.12791561 0.2839783  0.48756462 0.4418311  0.53722961 0.06011888
  0.60905072 0.07475899 0.64568632 0.41873462]]

Covariance Matrix:
[[ 0.06344564 -0.01592471 -0.06231582  0.01331636]
 [-0.01592471  0.06452534 -0.01713172 -0.00684157]
 [-0.06231582 -0.01713172  0.1116285  -0.00028412]
 [ 0.01331636 -0.00684157 -0.00028412  0.04316511]]

Correlation Matrix:
[[ 1.         -0.2488889  -0.74047409  0.25445915]
 [-0.2488889   1.         -0.20185902 -0.12963556]
 [-0.74047409 -0.20185902  1.         -0.00409306]
 [ 0.25445915 -0.12963556 -0.00409306  1.        ]]
